name: Generate GitHub Stats

on:
  workflow_dispatch:   # manual trigger
  schedule:
    - cron: "0 0 * * *"   # daily at midnight UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Stats
        uses: yoshi389111/github-profile-stats-generator@v1
        with:
          username: tejaswanirai
          template: default

      - name: Setup GitHub token
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit & Push
        run: |
          git add stats.svg top-langs.svg
          git commit -m "update stats" || echo "no changes"
          git push
